[build.environment]
  NPM_FLAGS = "--version"
[build]
  command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm build"
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "sameorigin"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/blog/options-you-have-for-setting-up-your-own-website"
  to = "/blog/wix-wordpress-jamstack-oh-my/"

[[redirects]]
  from = "/blog/how-i-built-this-website-with-sapperjs"
  to = "/blog/why-i-chose-sapperjs-for-my-website-and-what-ive-learned-about-the-framework-so-far/"

[[redirects]]
  from = "/categories/personal-development"
  to = "/categories/lifestyle/"
